#!/bin/bash

terraform validate

deploy_app() {
    terraform plan \
        -var "do_token=${DO_PAT}" \
        -var "mongo_uri=${MONGO_URI}"
    terraform apply \
        -var "do_token=${DO_PAT}" \
        -var "mongo_uri=${MONGO_URI}"
    # terraform destroy \
        # -var "do_token=${DO_PAT}" \
        # -var "mongo_uri=${MONGO_URI}"
}
